### ISSUE TITLE
Handle more complex browser-compat-data

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-css-languageservice#107]
Continuation of #105

There are a few cases in the data that we don't handle.

1. Support was added under an experimental flag
  - For those that have become standardized, we can just display the latest supported version. (e.g., supported through flag in ver 1, become officially supported in v2, we can just show Browser V2)
  - For those that haven't become standardized. We need to find a way to display the information. For example `Chrome 61 with flag`. @aeschli What do you think? 
2. Support is not chronological, for example: https://github.com/mdn/browser-compat-data/issues/1596. We can worry about this later, as `mdn/browser-compat-data` seem to have plan for enforcing certain linting rules on the order of support data.

**Comment by aeschli** [comment]
Closing, no plans for now
