### ISSUE TITLE
@counter-style rule is missing

### ISSUE THREAD

**Issue by xfq** [microsoft/vscode-css-languageservice#113]
VS Code version: 1.25.0

<img width="403" alt="counter-style" src="https://user-images.githubusercontent.com/2863444/42504179-78471ce8-846d-11e8-8767-521cbe7f72a8.png">

Docs on MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style

**Comment by aeschli** [comment]
This work now.
