### ISSUE TITLE
Convert to use MarkedString

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-css-languageservice#132]
`MarkedString` is deprecated and causes confusion. See https://github.com/Microsoft/vscode/issues/62332

**Comment by aeschli** [comment]
Implementation note:
MarkedString might not be supported by every client of the service. To let clients specify what capabilities they have, I started in the JSON-languageservice that the client can pass in a ClientCapabilty to the service: See https://github.com/Microsoft/vscode-json-languageservice/blob/7b0bc0dcf45ab6411429e986716f969f92773850/src/jsonLanguageTypes.ts#L207

**Comment by octref** [comment]
Will do this together with HTML.

Also, https://github.com/Microsoft/vscode-html-languageservice/issues/12 needs to be handled as well. Per the policy we need to show warning when linking to non-Microsoft websites.
