### ISSUE TITLE
Ctrl+click (go to file) doesn't work for saas-loader ~ imports (node_modules)

### ISSUE THREAD

**Issue by 2-5** [microsoft/vscode-css-languageservice#136]
Trying to Ctrl+click on the imported module name fails:
```scss
@import '~bootstrap/scss/bootstrap';
```
with this error:

```
Unable to open '_bootstrap.scss': File not found (file:///PROJECT/src/styles/~bootstrap/scss/_bootstrap.scss).
```

The reason is that I'm using `webpack` with `saas-loader`, and `saas-loader` treats an import path starting with `~` as an import from `node_modules`: https://github.com/webpack-contrib/sass-loader#imports

So the actual location from where the import should be loaded is:
```
file:///PROJECT/node_modules/bootstrap/scss/_bootstrap.scss
```

**Comment by penx** [comment]
@aeschli any thoughts on this?

I would assume, when encountering a path starting with ~, you can revert to node module resolution?

Do you want a more thorough example? Or any pointers on where this could be solved?

FWIW I made [css-hyperclick](https://atom.io/packages/css-hyperclick) for Atom but have since moved to using VSCode. I'd consider contributing this fix but looks like there may be a learning curve...!

**Comment by penx** [comment]
From what I can see, uriStringNodeToDocumentLink:

https://github.com/Microsoft/vscode-css-languageservice/blob/69884c1d4cd5bf96de71b576587667853600bd50/src/services/cssNavigation.ts#L236
...
https://github.com/Microsoft/vscode-css-languageservice/blob/69884c1d4cd5bf96de71b576587667853600bd50/src/services/cssNavigation.ts#L262-L271

calls resolveReference here:

[vscode/extensions/css-language-features/server/src/utils/documentContext.ts](https://github.com/Microsoft/vscode/blob/6906d7e3b26e807eedc566944de344e0e53a39bc/extensions/css-language-features/server/src/utils/documentContext.ts#L26-L35)

So I think we'd need to hand over to node module resolution in one of these files. I think at the start of documentContext's resolveReference function, 

```js
if (ref[0] === '~') {
  return nodeModuleResolution.resolve(base, ref.substring(1))
```

It would be good to see how this is being handled for resolveReference in typescript/javascript and use the same technique - but I've not been able to find this yet.

**Comment by penx** [comment]
Related:

> Thus you can import your Sass modules from node_modules. Just prepend them with a ~ to tell webpack that this is not a relative import
> ```scss
> @import "~bootstrap/dist/css/bootstrap";
>```
https://github.com/webpack-contrib/sass-loader#imports

**Comment by penx** [comment]
I have this working and have opened a PR https://github.com/Microsoft/vscode/pull/70693

**Comment by penx** [comment]
@aeschli any chance of some input on the PR for this? Has been open more than 3 weeks.

Microsoft/vscode#70693

Thanks!

**Comment by penx** [comment]
@aeschli there are still issues with this, please see my comment on https://github.com/microsoft/vscode/pull/70693#issuecomment-510838348

Maybe we can reopen this or I can open a new issue for this if you'd prefer?

**Comment by aeschli** [comment]
Let's create a new issue...

**Comment by mciesin** [comment]
@penx @aeschli 
when you prefix your path with `~`, webpack not only searches for the file inside the node_modules directory, but also considers aliases defined using `webpack.config.js`.

This behavior has already been taken into account for JS - you can inform IntelliSense about your aliases using [jsconfig](https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases). Would it be possible to e.g. retrieve information about webpack aliases from jsconfig for *.scss files?

**Comment by dimitir** [comment]
try vs code CSS Navigation
