### ISSUE TITLE
[FEAT] SASS syntax support

### ISSUE THREAD

**Issue by teoxoy** [microsoft/vscode-css-languageservice#158]
Currently only SCSS syntax is supported but not SASS.

**Comment by aeschli** [comment]
Yes, sure, if you find an elegant solution, that would be welcome. There are various aspects to is:
- parsing the input and bringing it to the same AST. The challenge is how to avoid to duplicate most of the code of the css/less/scssParser, without making it more complex.
- adopt all code that generates code (completions, code actions).

If you want to experiment that would be great, but before committing to it I'd like to see the approach on how to do the parser. If the code gets overly complex, I'd rather suggest to do it in a separate project.

**Comment by Teoxoy** [comment]
I will look into it. It will take some time as I currently have another project to focus on but I would like to implement the SASS syntax nonetheless.

**Comment by SpectralKH** [comment]
@aeschii I'm not really knowledgeable about this, but in terms of parsing, shouldn't it be pretty possible to just put that into the existing SCSS files? All you need to do, if I'm not mistaken, is to check for newlines instead of semicolons, and newlines+indent changes instead of curly braces. Then you could do the same input into the AST as you would with SCSS. Am I correct about that?

**Comment by aeschli** [comment]
@SpectralKH I'm no expert either. My understanding is that SASS has some more differences as outlined here: https://www.sitepoint.com/whats-difference-sass-scss/
Then there is stuff like error recovery, reporting and the behaviour of hovers and code completion which are all tuned for SCSS.

**Comment by SpectralKH** [comment]
@aeschli I originally thought the only difference was that it uses indentation instead of curly braces and newlines instead of semicolons. [The documentation](https://sass-lang.com/documentation/syntax) says this, though:
> In general, any time you’d write curly braces in CSS or SCSS, you can just indent one level deeper in the indented syntax. And any time a line ends, that counts as a semicolon. There are also a few additional differences in the indented syntax that are noted throughout the reference.

**Comment by Teoxoy** [comment]
I said I will be willing to implement this but unfortunately I haven't found the time to do so and now it's no longer a priority for me.
Feel free to close the issue if no one wants to pick this up.

**Comment by aeschli** [comment]
Closing as out-of-scope
