### ISSUE TITLE
Is there a way to use this plugin with css-in-js?

### ISSUE THREAD

**Issue by alextes** [microsoft/vscode-css-languageservice#168]
I use it with https://github.com/neoclide/coc.nvim but that shouldn't change much.

**Comment by aeschli** [comment]
vscode-css-languageservice works on a css/less/scss input file and it creates proposals and code actions for such content.

So I'm not sure how it could be used for css-in-js where the the embedded css is similar to css but not quite...

**Comment by alextes** [comment]
I should have clarified that I'm talking about only libraries that use strings to write css, in which case the CSS is character for character css/less/scss, in which case I'm not sure what isn't quite the same. I realize thinking about this more that the most useful feature would actually seem to me completion and snippets but I'd guess those actually require vscode to send text to this service, whereas this service only implements the logic responding to said input. I'll reopen in coc.nvim.
