### ISSUE TITLE
regression: "unknownProperty" diagnostics loses case sensitivity for a given symbol

### ISSUE THREAD

**Issue by tomrav** [microsoft/vscode-css-languageservice#175]
I am maintaining a [vscode plugin](https://github.com/wix/stylable-intelligence) that utilizes the programmatic API of this service. As part of our extended API on top of CSS, I am actively filtering some warnings from the service, while allowing others to pass.

I have noticed a change in behavior with the symbol names shown in the diagnostic. The original symbol was capitalized, while the diagnostic loses the casing.

See example here, `Blah` turns to `blah`:
![Screen Shot 2019-09-02 at 18 02 51 copy](https://user-images.githubusercontent.com/6399886/64123267-93d83580-cdac-11e9-9275-a90acef8642d.png)

I can handle this change on my end, and filter for my expected results, but I can't help but wonder if this is an unintended side effect of another change (I suspect PR #144 might be related).

Thanks!

**Comment by octref** [comment]
This doesn't happen in latest version — let me know if it doesn't fix your case.
