### ISSUE TITLE
Add support for updating css/scss import paths when file is moved or renamed

### ISSUE THREAD

**Issue by nicholasengleman** [microsoft/vscode-css-languageservice#177]
It would be very convenient if the paths for imported css and scss files could get updated whenever the files are moved or renamed.

**Comment by aeschli** [comment]
closing as out-of-scope

**Comment by kiril-daskalov** [comment]
Hello guys!

This is annoying! Is it VS code problem or something else?

**Comment by cakeseller** [comment]
@aeschli hi. Excuse me, but why this issue was closed as out-of-scope? This looks like a very handy feature.

**Comment by aeschli** [comment]
Out of scope because of the work needed to implement. Also it would probably have some performance implications. Every file operation that we detect would mean to go through every CSS/SCC file to check if a import needs to be changed.
If you are interested to work on it, I'm happy to take a PR.
