### ISSUE TITLE
[less] parsing error for using parametric mixins

### ISSUE THREAD

**Issue by octref** [microsoft/vscode-css-languageservice#186]
Originally reported at https://github.com/microsoft/vscode/issues/68324

This generates a warning:

```less
.foo  {
  .bar ();
}
```

Whereas this is fine:

```less
.foo  {
  .bar();
}
```

Both compiles with Less.

@matthew-dean If you do have time, would you mind taking a look? Think your PR already solved the original issues' first two cases, would be great if the last case can be supported too.

**Comment by matthew-dean** [comment]
@octref If I can find the time, for sure!
