### ISSUE TITLE
Variable interpolation incorrectly recognized as ID selector

### ISSUE THREAD

**Issue by aNickzz** [microsoft/vscode-css-languageservice#189]
Pretty much a duplicate of https://github.com/microsoft/vscode/issues/75905, however @octref  suggested I open a new issue, and the contributing guide lead me to this repo.

Selectors in SCSS composed of variables wrapped in `#{}` are incorrectly identified as ID selectors, which triggers the error / warning about using ID selectors.

> Selectors should not contain IDs because these rules are too tightly coupled with the HTML.

Tested on the latest insiders build:

![image](https://user-images.githubusercontent.com/15243523/67464202-7e83d700-f68a-11e9-9832-6e2ac3d20309.png)

A check should be introduced on this logic to recognize when a `#` is used as part of an ID vs part of `#{}` variable interpolation

- VSCode Version: 1.40.0-insider (user setup)
- Commit: b53811e67e65c6a564a80e1c412ca2b13de02907
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open a new tab and select the "SCSS" language
2. Enter the following code:

```scss
@for $i from 0 to 9 {
	.enterActive &:nth-child(#{$i}) {
		transition-delay: $i * 30ms;
	}
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Seems like the original issue still reproes, will close this in favor of that one.

**Comment by octref** [comment]
Thanks! I didn't enable the rule explicitly, which would have reproduced the problem.
