### ISSUE TITLE
Themes not respecting new @apply support

### ISSUE THREAD

**Issue by philippelesaux** [Microsoft/vscode-css-languageservice#19]
It looks like themes are not respecting the new @apply rules, at least in regards to color-coding.

Using 1.8.0 stable

![screen shot 2016-12-16 at 9 58 51 am](https://cloud.githubusercontent.com/assets/13442851/21273215/81c83eae-c390-11e6-8587-db99f0308e1f.png)

edit: This is the default dark theme, but I see the issue in Dracula, Light+, Monokai, and others

**Comment by aeschli** [comment]
Syntax coloring is not provided by vscode-css-languageservice but by a text mate grammar.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode#17850
