### ISSUE TITLE
Disable ignoreComment option

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode-css-languageservice#2]
Hello,

I'm working on improving [vscode-less](https://github.com/mrmlnc/vscode-less) extension and want to disable autocompletion in the comments.

How to I can disable `ignoreComment` option for `parseStylesheet`?

**Comment by aeschli** [comment]
To find out where is a comment you would use the scanner.
The stylesheet is an AST representation that does not contain any comments.
