### ISSUE TITLE
[bug] variables before use and forward

### ISSUE THREAD

**Issue by MattMcAdams** [microsoft/vscode-css-languageservice#203]
Given the following example scss:
```scss
$example: 'random-string';

@use 'test' with (
  $config: $example
);
```
`@use` is flagged with a validation error `at-rule or selector expected` from `scss(css-ruleorselectorexpected)`

You should be allowed to define variables before the `@use` or `@forward` statements for use in module configuration, and the above will compile (given it has real data) using dart sass

From Sass documentation:
> A stylesheet’s `@use` rules must come before any rules other than `@forward`, including style rules. However, you can declare variables before `@use` rules to use when configuring modules.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5575R CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (3.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
comment-anchors|Exo|1.6.1
php-debug|fel|1.13.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
vscode-scss|mrm|0.8.1
atom-keybindings|ms-|3.0.6
polacode|pnp|0.3.4
vscode-css-peek|pra|3.0.2
code-settings-sync|Sha|3.4.3
stylelint|shi|0.51.0
html-css-class-completion|Zig|1.19.0

(3 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
I fixed this by no longer enforce in the parser that @use or @forward rule are first.
This check should be done in a linter (likly the scss watcher that users run).
