### ISSUE TITLE
Development Enviroment

### ISSUE THREAD

**Issue by paull39** [microsoft/vscode-css-languageservice#205]
Hey,
thanks for your great work. Your Software is part of my everyday work.

I would like to have some kind of development enviroment to get my hands on this repo and solve some issues.
Do you mind giving out some hints how you develop?

**Comment by aeschli** [comment]
Thanks for the positive feedback!
See https://github.com/microsoft/vscode-css-languageservice/blob/master/README.md#development for instructions on how to work with the code.
