### ISSUE TITLE
Css el > el and el + el hover are the same

### ISSUE THREAD

**Issue by CaselIT** [Microsoft/vscode-css-languageservice#21]
vscode: v1.9.0

It seems that the hover text for both `el > el` and `el + el` are the same:
![image](https://cloud.githubusercontent.com/assets/16175304/22739428/e7497f68-ee0b-11e6-9009-6104c3bfcd35.png)
![image](https://cloud.githubusercontent.com/assets/16175304/22739441/f3fe5d50-ee0b-11e6-9581-44e2d892c4db.png)

In particular I think that the hoover for `el > el` is the wrong one, since the `<p>` in this case should be indented.

I'm not sure if this is the right place, or if it's better to move it to the vscode repo.

**Comment by rocifier** [comment]
Hi, this is a confirmed bug which I am currently fixing. Please see here https://github.com/Microsoft/vscode/issues/22835#issuecomment-290590310

**Comment by CaselIT** [comment]
Thanks,
I'll close this issue then
