### ISSUE TITLE
Escape html entities in textDocument/hover

### ISSUE THREAD

**Issue by rwols** [microsoft/vscode-css-languageservice#217]
When doing a textDocument/hover on e.g. `background-color`, I'm getting this:
```js
{
    "contents": {
        "kind": "markdown",
        "value": "Sets the background color of an element.\n\nSyntax: <color>\n\n[MDN Reference](https://developer.mozilla.org/docs/Web/CSS/background-color)"
    },
    "range": {
        "end": {
            "character": 54,
            "line": 32
        },
        "start": {
            "character": 4,
            "line": 32
        }
    }
}
```
The `"value"` confuses our markdown parser because it contains `<color>`. It is interpreted as a html entity. Please escape html tags.

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode-css-languageservice/commit/82caae4cb2bbbdc86b0ba7dad7ef310e31ccf352
