### ISSUE TITLE
Suggestions are polluted

### ISSUE THREAD

**Issue by clubajax** [microsoft/vscode-css-languageservice#221]
The autocomplete suggestion for SCSS are very frustrating. Basic properties are buried below rare, esoteric, or invalid properties.

Additionally, basic elements (div, span, etc) do not come up in the list at all.

Below I am attempting to access: background-color, margin, and font/family/weight.

![scss-bg](https://user-images.githubusercontent.com/290747/92613036-1d53fa80-f280-11ea-9c59-63305098318a.png)
![scss-margin](https://user-images.githubusercontent.com/290747/92613041-1e852780-f280-11ea-9077-0f4936457c46.png)
![scss-font](https://user-images.githubusercontent.com/290747/92613045-1e852780-f280-11ea-8759-8cf561a28c73.png)

It would be nice if there was:
- A priority attached to common properties
- Properties came up by oft-used
- There was a way to customize the suggestion list (whitelist or blacklist)

**Comment by aeschli** [comment]
This has been fixed, please try the latest version of VSCode insiders (new stable coming soon)
