### ISSUE TITLE
`color-scheme` CSS property not recognized

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/vscode-css-languageservice#223]
![image](https://user-images.githubusercontent.com/10532611/96700020-3aa3da80-138f-11eb-813b-02599e398003.png)

The `color-scheme` property sets the default appearance of native form elements. It's supported in Chrome and Safari.

See
- Article: https://web.dev/color-scheme/#the-color-scheme-css-property
- Spec: https://drafts.csswg.org/css-color-adjust/#color-scheme-prop

**Comment by aeschli** [comment]
We generate our table of properties from https://github.com/mdn/data.

Looks like `color-scheme` is still experimental.

Note that you can use the `css.lint.validProperties` setting to avoid the warning.
