### ISSUE TITLE
Would you recommend to disable VS Code css.validate when using StyleLint rules? 

### ISSUE THREAD

**Issue by dcorb** [microsoft/vscode-css-languageservice#225]
VScode only supports around 20 linting rules (and I guess they are covered by StyleLint)
https://github.com/microsoft/vscode-css-languageservice/blob/5f909a88efd6b097c3e40c0f429326ac98be3ef1/src/services/lintRules.ts#L31-L51

Is there any benefit to have both `css.validate` and StyleLint at the same time?

We noticed there is double-reporting if `css.validate` is enabled

![image](https://user-images.githubusercontent.com/881333/97857032-d0cbef00-1d05-11eb-8776-2631f8d69bfb.png)

I opened also this other issue in VSCode stylelint extension, https://github.com/stylelint/vscode-stylelint/issues/149

**Comment by aeschli** [comment]
Yes, we recommend to disable build-in liniting rules if you use a more powerful linter.
`css.validate` will also turn off syntax checking. Ig you just want to disable linting rules, use the `css.lint.*` settings.
