### ISSUE TITLE
Upgrade vscode-languageserver-types

### ISSUE THREAD

**Issue by dummdidumm** [microsoft/vscode-css-languageservice#229]
`3.16.0` of `vscode-languageserver-types` was released. It contains the latest and now stable typings. The CSS language service contains typings of an early `3.16.0-next`-Version which are outdated. For example the `Diagnostic` interface has a property `code` which is `string | number | DiagnosticCode`. That last one seems to be introduced experimentally and was removed from `3.16.0`. I therefore cannot update to the latest `vscode-languageserver-types` version currently.

The same applies for the `vscode-html-languageservice` btw.

**Comment by aeschli** [comment]
Released 5.0.0 with the types update
