### ISSUE TITLE
`@apply` throws validation errors in SCSS

### ISSUE THREAD

**Issue by lacolaco** [microsoft/vscode-css-languageservice#232]
I want to use the `@apply` directive in SCSS files. It's definitely valid in `sass` compilation but VSCode editor shows errors like below.

![image](https://user-images.githubusercontent.com/1529180/104975592-6b52e900-5a3e-11eb-9382-40ee27db5319.png)

These errors are disappeared when I disable `SCSS: Validate` flag in settings. How can I use the `@appy` with built-in validations?

**Comment by lacolaco** [comment]
Maybe will be solved by #214

**Comment by aeschli** [comment]
Fixed. `@apply` is now an unknown at rule, which is ignored (unless you set the linter setting)
