### ISSUE TITLE
Question: Any plans to support stylus ?

### ISSUE THREAD

**Issue by PodaruDragos** [microsoft/vscode-css-languageservice#234]
I know this has been asked before, but a lot of time has passed since then.
Do you consider adding it ?

If not can someone explain why ? people still use stylus as far as I know (myself included)

**Comment by aeschli** [comment]
Sorry, no plans. Supporting a new language is a lot of work. Not only implement but especially to maintain. The VSCode team doesn't have the time budget for it. If anyone is interested to work on it, that would be great. That said, there are VSCode stylus extensions out there, with more than just syntax highlighting, e.g. https://github.com/d4rkr00t/language-stylus. Maybe best is to support these.
