### ISSUE TITLE
Linting Issue with GOSUB

### ISSUE THREAD

**Issue by jo005597** [microsoft/vscode-css-languageservice#240]
When using a LOCAL Subroutine the following syntax is allowed to define it:

`Local Subroutine GenerateAlert(message,includeException)`

To use the local subroutine in OpenQM one would:

`GOSUB GenerateAlert("Failure accessing client account!",@TRUE)`

The Linter in VSCODE is reporting that the Label does not exist resulting in syntax errors being reported when there are none.

**Comment by aeschli** [comment]
I don't think that issue is related to the vscode css language service,

Please file it against the extension that provides the OpenQM  linter
