### ISSUE TITLE
CSS Language service seems to return all items for "@" on doComplete

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-css-languageservice#246]
Im a maintainer of the VSCode Styled Components extension.
I've noticed that for our [getCompletionItems](https://github.com/microsoft/typescript-styled-plugin/blob/main/src/_language-service.ts#L231-L232) CSS Language Service seems to return all items no matter where the cursor is sitting on. 

Should it not be filtering down based on what has been typed already?
Screenshot below
![image](https://user-images.githubusercontent.com/936006/126901706-d433b5a5-ccde-4680-a01f-23e5f29c58ac.png)

v5.11

**Comment by aeschli** [comment]
Filtering of proposals happens on the UI side. The editor UI can decide on various strategies such as prefix match, similarity match, camelCase match...
