### ISSUE TITLE
Provide `textEdit` in completion item

### ISSUE THREAD

**Issue by johnsoncodehk** [microsoft/vscode-css-languageservice#265]
Currently vscode-css-languageservice do not provide textEdit in completion item, scss document completion text replace range depends on wordPattern from vscode scss language configuration.

In vanilla scss document, it's working good, but if scss is embedded language in a document, vscode don't know the completion item is for scss language, so vscode don't apply replace range by scss wordPattern. In this case vscode can't show expected scss completions.

<img width="304" alt="螢幕截圖 2022-02-13 06 35 17" src="https://user-images.githubusercontent.com/16279759/153730803-90953977-45de-43ba-8ded-16191bf0f4dc.png">
 
To fix this problem, I was calculate `textEdit` for css completion item before send it to language client.

https://github.com/johnsoncodehk/volar/blob/573dad2efb6faa5fcb68e147498f1a2e58f65b3e/packages/vscode-vue-languageservice/src/services/completion.ts#L649-L666

But this way is unreliable, I've had some particular edge cases before. (But I forgot what actually happen)
I hope we can have `textEdit` from vscode-css-languageservice, so as downstream we don't need to care about css completion replace rules.

**Comment by aeschli** [comment]
If you want to work on a PR that would be great.

**Comment by johnsoncodehk** [comment]
I'll survey it after finish backlog. :)
