### ISSUE TITLE
Support for CSS @layer rule 

### ISSUE THREAD

**Issue by praveenpuglia** [microsoft/vscode-css-languageservice#274]
Currently when I try to use `@layer`, it shows this error. - `Unknown at rule`
<img width="387" alt="image" src="https://user-images.githubusercontent.com/313363/173119054-6d25d775-591f-4755-93c0-cdab6f50ed48.png">

With the browser support coming up fast for this, we should totally support it. 
MDN Link - https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
Spec Link - https://drafts.csswg.org/css-cascade-5/#layering

**Comment by Mitchman215** [comment]
You probably should open this issue at [web-custom-data repo](https://github.com/microsoft/vscode-custom-data/tree/main/web-data) since that's where the data for CSS entities are. 

From this repo's readme: 
> Note: All CSS entities (properties, at-rules, etc) are sourced from https://github.com/microsoft/vscode-custom-data/tree/master/web-data and transpiled here. For adding new property or fixing existing properties' completion/hover description, please open PR there).

**Comment by Mitchman215** [comment]
Both the parser and the web-custom-data probably need to be updated in order to accommodate this change. From my understanding, web-custom-data is responsible for the description and documentation that displays on hover and intellisense. Then again, I don't work for this project so I could be wrong.

**Comment by praveenpuglia** [comment]
The changes I made as part of the PR already takes care of the making sure the css language service knows about `@layer` and on hover it shows the description as well. 

@aeschli and @octref would know better.

**Comment by praveenpuglia** [comment]
Linking #276
