### ISSUE TITLE
Add support to the css contain property

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode-css-languageservice#31]
`contain` property is marked as unknown property.

**Specs:**
- https://drafts.csswg.org/css-containment/

**Other links:**
- https://developer.mozilla.org/en-US/docs/Web/CSS/contain
- https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom#containment

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/10840
