### ISSUE TITLE
Traverse Stylesheet

### ISSUE THREAD

**Issue by Viijay-Kr** [microsoft/vscode-css-languageservice#323]
Is there a way to traverse the AST returned by the parser ? Does this library expose any function to do that ?

If not is there any plan to include style sheet traversal logic inside the scope of this project or 
At least exposing StyleSheet type definitions would be useful to create custom traversal logic outside the scope of this project

**Comment by aeschli** [comment]
Sorry, there are no plans to make the AST public API. It's a lot of work to polish/document all the API and later to maintain it.
