### ISSUE TITLE
Support CSS5 `color-mix` function

### ISSUE THREAD

**Issue by zm-cttae** [microsoft/vscode-css-languageservice#348]
We need syntax highlighting and also edit snippets for `color-mix` - a CSS funtion which allows chromatic mixing of CSS colors:

*   [color-mix() - CSS: Cascading Style Sheets | MDN (mozilla.org)](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix)
*   [CSS Color Module Level 5 (w3c.github.io)](https://w3c.github.io/csswg-drafts/css-color-5/#color-mix)

**Comment by aeschli** [comment]
Snippet added by #349
Syntax highlighting feature request must be filed here: https://github.com/microsoft/vscode-css
