### ISSUE TITLE
attribute selectors with a namespaces do not parse

### ISSUE THREAD

**Issue by chriseppstein** [Microsoft/vscode-css-languageservice#36]
Attributes can have a namespace qualifier in order to select html attributes in a specific xml namespace. 

https://www.w3.org/TR/selectors/#attrnmsp

currently VS code shows an error that `] expected` when it encounters the namespace delimiter: `|`

**Comment by aeschli** [comment]
This is fixed with https://github.com/Microsoft/vscode-css-languageservice/commit/b017aa784b2c516d769935c85697d260bc2f7847
