### ISSUE TITLE
support nested @container 

### ISSUE THREAD

**Issue by liaoyinglong** [microsoft/vscode-css-languageservice#389]
the following code is worked in `sass` but get error in vscode
```scss
.box{
    @container (max-width: 800px) {
      height: 12px;
   }
}
```

### see the example
- worked: 
<img width="982" alt="image" src="https://github.com/microsoft/vscode-css-languageservice/assets/23382699/6670267c-0a07-4334-9414-78c5a87bf92d">

- get error in vscode: 
<img width="934" alt="image" src="https://github.com/microsoft/vscode-css-languageservice/assets/23382699/8a345d44-2e9e-4824-a79e-6fc89d4fba01">

### here is the playground link

sass

https://sass-lang.com/playground/#eJwzNNRLyq+o5lIAAofk/LySxMy81CIFjdzECt3yzJSSDCsFCwODggpNBYgaBYWM1Mz0jBIrBUOjggprkFgtVy0A3aQT7A==

less

https://lesscss.org/less-preview/#eyJjb2RlIjoiI2xpYigpIHtcbiAgICAuY29sb3JzKCkge1xuICAgICAgQHByaW1hcnk6IGJsdWU7XG4gICAgICBAc2Vjb25kYXJ5OiBncmVlbjtcbiAgICB9XG4gICAgLnJ1bGVzKEBzaXplKSB7XG4gICAgICBib3JkZXI6IEBzaXplIHNvbGlkIHdoaXRlO1xuICAgIH1cbiAgfVxuICBcbiAgLmJveCB3aGVuICgjbGliLmNvbG9yc1tAcHJpbWFyeV0gPSBibHVlKSB7XG4gICAgd2lkdGg6IDEwMHB4O1xuICAgIGhlaWdodDogKCR3aWR0aCAvIDIpO1xuICB9XG4gIFxuICAuYmFyOmV4dGVuZCguYm94KSB7XG4gICAgQG1lZGlhIChtaW4td2lkdGg6IDYwMHB4KSB7XG4gICAgICB3aWR0aDogMjAwcHg7XG4gICAgICAjbGliLnJ1bGVzKDFweCk7XG4gICAgfVxuICB9IiwiYWN0aXZlVmVyc2lvbiI6IjQuMi4wIiwibWF0aCI6InBhcmVucy1kaXZpc2lvbiIsInN0cmljdFVuaXRzIjpmYWxzZX0=

**Comment by aeschli** [comment]
Fixed by #390
