### ISSUE TITLE
Please add support for @supports rule

### ISSUE THREAD

**Issue by codingcircus** [Microsoft/vscode-css-languageservice#39]
Hi, it would be really cool, if you could add support for the @supports rule (Feature Queries). It's supported by all major browsers, so it can be used in production.

**Comment by praveenpuglia** [comment]
@aeschli - I see it available in browsers.js. I still see [css] at rule unknown.

**Comment by praveenpuglia** [comment]
@aeschli - Guess a `_parseSupports` or similar is missing from [this](https://github.com/Microsoft/vscode-css-languageservice/blob/2729975f37d2f8abed2c3af20a7675070964fbb3/src/parser/cssParser.ts#L234-L244) and that's why even though browsers.js has entry for `@supports`, it still throws `at-rule unknown` error.

**Comment by praveenpuglia** [comment]
I tried writing the foundation to parse `@supports`. 
https://github.com/praveenpuglia/vscode-css-languageservice/commit/cd58aa91fe5659d5c66fa0d910dc25bed8912b02

Now I get a different error. I am sure the `_parseSupports` function needs to do more than whatever I have written in that function. My lack of understanding of the parser here. Needs help.

![image](https://user-images.githubusercontent.com/313363/29356756-ede43702-8292-11e7-85e5-17eaaef72326.png)

**Comment by aeschli** [comment]
So far you got it right. `_parseSupports` will have to consume the rest of supports rule, such as the expressions. This needs to happen according to the grammar as defined here: https://drafts.csswg.org/css-conditional-3/#at-supports

I can look into that later this month, if you want me to.

**Comment by praveenpuglia** [comment]
@aeschli that'll be great. I am a total noob at this. For now, should i raise a PR with whatever I have or leave it like that till you get back ?
