### ISSUE TITLE
Formatter deletes whitespace in CSS property

### ISSUE THREAD

**Issue by alex-kinokon** [microsoft/vscode-css-languageservice#394]
https://microsoft.github.io/monaco-editor/playground.html?source=v0.49.0#XQAAAAJUAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzUZ4RgmSaumWUF-TBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKikCFtZ2PcrbXwpoK8n2kLt92IKLKtU-Xcpr6FNj-9W8ErRBbvsRAt6Vja7u4nrlpdXavyzQnr-RvAkpKpA_WKabLfDkBOBukabI6q1jANmX0ITbxwUh6LJsu-nUD2XlBurYWleuq8DSIHYZCOLy5XG0jKSzkpD0tGJeMhjhg_e62_lg3vu1QJ4vnLUjG15IfzbBobesKGZcXDe3ur3p5IYrsvMD_95ylew

Right click to to open the command palette, choose “Format document”. The editor will remove the space between `" "` and `attr`, resulting in a `semi-colon expectedcss(css-semicolonexpected)` error.

**Comment by aeschli** [comment]
This seems to be fixed in the latest VS Code Insiders.
Version: 1.91.0-insider
Commit: 63d06667600a2c40245a0ab1f9e2ea816d2fe849
Date: 2024-06-21T10:25:39.732Z

and in the latest monaco editor (0.50 stable)
