### ISSUE TITLE
Maintaining browser support data

### ISSUE THREAD

**Issue by praveenpuglia** [Microsoft/vscode-css-languageservice#40]
Code 1.15 just released. At the time of adding support for `display: flow-root` to languageservice, I didn't have information about Opera 45 supporting it. 

Today I went back to MDN to see it is now supported in Opera 45. This means the property now has to be manually told to support this info in `css-schema.xml` file.

And not just this but anything that needs change. Currently there are some problems.

1. It's a tedious manual work.
2. Mobile support data ins't even present. 
3. MDN's browser support tables aren't 100% reliable. 

Can we build a system in the languageservice that automatically pulls in data from cainuse or any other service and then we don't need to painstakingly look for changes in browser support and manually update it?

**Comment by aeschli** [comment]
https://github.com/mdn/browser-compat-data contains the latest compatibility data from MDN. I didn't have the chance to invest in using that data. If you want to look into it that would be awesome!

**Comment by praveenpuglia** [comment]
Their data seems to be pretty limited at the moment. https://github.com/mdn/browser-compat-data/tree/master/css/properties

**Comment by praveenpuglia** [comment]
A lot of properties has been added. We can get browser data but not the description of the properties. Can we plan something around this?

**Comment by connorshea** [comment]
The browser-compat-data project is now at 80% completion (as in, 80% of the old compat tables on MDN have been updated to the new format), and it should cover support for almost all CSS properties, at-rules, etc. :) It’s not entirely complete but it’s very close.

**Comment by praveenpuglia** [comment]
I am closing this issue in favour of #68. @octref has already made some progress using the MDN data which is live in latest stable. I am sure he has planned a bunch of things already.
