### ISSUE TITLE
Support for -webkit-font-smoothing

### ISSUE THREAD

**Issue by alexlur** [Microsoft/vscode-css-languageservice#43]
`font-smoothing` is not part of the standard, but its prefixed version well supported by webkit / Blink based browsers for a while.
<img width="483" alt="capture d ecran 2017-08-18 a 21 57 04" src="https://user-images.githubusercontent.com/8125011/29482521-70feefe6-8460-11e7-99e6-3902fafa4c11.png">

Any plan to add it?

**Comment by alexlur** [comment]
Ironically, I need this property to write userstyles to “unfix” websites abusing `webkit-font-smoothing: antialiased`.

**Comment by alexlur** [comment]
Now that I think about it, what about an API to add custom CSS properties?

**Comment by aeschli** [comment]
@alexlur In VS Code you could do that by adding snippets...

**Comment by alexlur** [comment]
@aeschli This is for `monaco-editor`, not Visual Studio Code.

**Comment by aeschli** [comment]
@alexlur Oh, actually, all you want is that the language server stops warning about it, right?
IMO that makes sense, we should add a `css.lint.ignoredProperties` list.
