### ISSUE TITLE
Add support for CSS next

### ISSUE THREAD

**Issue by szimek** [microsoft/vscode-css-languageservice#47]
According to [this comment](https://github.com/Microsoft/vscode/issues/3907#issuecomment-278026682) one should create separate issues for individual features, so here it is :)

It would be great if [cssnext nesting](http://cssnext.io/features/#nesting) was supported. Currently, such syntax causes VS Code to report it as an error, e.g.

<img width="369" alt="vs-code-css-next-syntax-error" src="https://user-images.githubusercontent.com/9873/31931705-542f2e58-b8a4-11e7-8648-a2eb4d06132c.png">

Are cssnext features in scope of this CSS language service or should they be implemented as an extension instead?

**Comment by aeschli** [comment]
CSSnext support is not planned. But we want to support whatever gets added to CSS specs.

**Comment by chriseppstein** [comment]
@aeschli I think this is good, it would be confusing for developers to not get syntax errors for invalid syntax intended for browsers unless they've opted into support for future features. That said, these features are usually on track to become css and so it's not entirely wasted effort to build support for the new features a bit early -- hidden behind feature flags to which devs would have to opt in.

Another approach would be for the css-next community to maintain a fork of this project, ideally with a git branch per future spec feature and a merge branch for release and when these specs reach maturity a PR could be submitted.

**Comment by praveenpuglia** [comment]
Couldn't this be made into an extension of some sort?

**Comment by sorenhoyer** [comment]
I would love cssnext support as well - if not built-in, then in an extension of some sort. cssnext really is the most logical pick today, over LESS and SASS imo.

**Comment by onetrev** [comment]
Hey @praveenpuglia @sorenhoyer and @szimek ... There is support for CSSNext with this [PostCSS extension](https://github.com/MhMadHamster/vscode-postcss-language).

Unfortunately, as per the usual with VS Code not supporting _cross file references ('imports')_, you still can't get custom properties / variable autocomplete or Go To Declaration and such. But it's a start. It would be great to see more PostCSS support added to this extension or others created, as I agree it's very much the logical pick today and it's really gaining steam -- fast!

**Comment by szimek** [comment]
@onetrev Like you've noticed [yourself](https://github.com/MhMadHamster/vscode-postcss-language/issues/18#issuecomment-354724555), this `vscode-postcss-language` extension doesn't really support cssnext :/

**Comment by EECOLOR** [comment]
Would be nice if we could add these kinds of things using [custom data](https://github.com/microsoft/vscode-css-languageservice/blob/master/docs/customData.md).

**Comment by aeschli** [comment]
Closing as out-of-scope
