### ISSUE TITLE
Feature request: setting to disable features like jump to definition/find references

### ISSUE THREAD

**Issue by rictic** [Microsoft/vscode-css-languageservice#55]
I'm implementing a language service that includes features for jumping to definition / find references with CSS Custom Properties, and I'm finding that the built in CSS Languageservice clashes with the results.

e.g. jump to definition will give two results for the same location with slightly different ranges, turning an instant jump into an interaction with a menu.

(Our language service understands HTML Imports, which is very useful for our users, otherwise I'd just turn off our CSS features in our VSCode plugin and defer to the vscode css languageservice.)

**Comment by aeschli** [comment]
The css language service is just a library and the user of the library decides when and and what document location to use it.
If this is about the css language *server* (not service), please file your suggestion against https://github.com/Microsoft/vscode
