### ISSUE TITLE
Less :matches() is not supported

### ISSUE THREAD

**Issue by proteriax** [microsoft/vscode-css-languageservice#56]
![image](https://user-images.githubusercontent.com/8125011/33914889-55b47954-df6e-11e7-8c0a-9aea9224d8d1.png)

Error is `) expected.`

**Comment by octref** [comment]
`:matches` is still in Working Draft phase and the spec is constantly being updated:

https://drafts.csswg.org/selectors-4/#selector-list

And it does not have much browser coverage either:

https://caniuse.com/#feat=css-matches-pseudo

So we would like to postpone the support until it gets more support from browser vendors or becomes a more formal spec.

**Comment by octref** [comment]
Think I should keep the issue open and add it to backlog instead.

**Comment by proteriax** [comment]
According to caniuse.com, it is now supported by browsers of over 94.19% users globally.

**Comment by Semigradsky** [comment]
@proteriax  For me (vscode 1.63.2) there are no errors.
![image](https://user-images.githubusercontent.com/1198848/149950949-04b1ee14-b256-4325-a084-b33ded040f21.png)

Also `:matches()` was renamed to `:is()` - https://caniuse.com/css-matches-pseudo

**Comment by aeschli** [comment]
Thanks for reporting @Semigradsky , closing the issue then.
