### ISSUE TITLE
Auto complete suggestions project wide

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode-css-languageservice#6]
This is a feature request, I'd like to auto-complete to work project wide. 

I think it should not try to be overtly clever, e.g. following import statements such as `@import "../library.scss";` instead it could just parse all *.scss *.less or *.css files for definitions and show those in auto-completion.

Currently this is extremly painful since I have React app where each component has own scss file, and it basically can't auto-complete anything.

I found the base function, which on each completion uses [doComplete(document: TextDocument, position: Position, styleSheet: nodes.Stylesheet)](https://github.com/Microsoft/vscode-css-languageservice/blob/master/src/services/cssCompletion.ts#L36)

I think one needs to cache the results of one textdocument, and keep tree of files parsed somewhere so that it doesn't need to parse all documents each time doComplete occurs.

**Comment by mrmlnc** [comment]
Hello, @Ciantic,

You have tried [vscode-scss](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss) extension?

**Comment by Ciantic** [comment]
@mrmlnc I did try to search for similar plugins just while ago, I wonder why I didn't find it? This is amazing, thanks!

**Comment by mrmlnc** [comment]
@Ciantic, because I released it yesterday 😄

**Comment by Tyriar** [comment]
:tada:
