### ISSUE TITLE
Published target compatibility with webpack/rollup

### ISSUE THREAD

**Issue by nadavwix** [Microsoft/vscode-css-languageservice#60]
The current publishing flow uses a tsconfig.json file (the one in src) and transpiles the module imports/exports to UMD.

When trying to bundle the `vscode-css-languageservice` npm package alongside `monaco-editor-core`, webpack errors about `require` being used in a way that cannot be staticly parsed.

Would you consider publishing to es2015 modules as well, and linking to that entry-point from the package.json's "module" field?

To match with other solutions online, `dist` folder could be something in the form:
`dist/umd/...`
`dist/esm/...`
etc.

The "module" field is being automatically picked by webpack, rollup, and other bundlers, and does not collide with the "main" field. It is only used during bundling.

**Comment by aeschli** [comment]
Not super cool as that would duplicate the number of files in the node module. No chance of configuring webpack to understand the UMD files?

**Comment by AviVahl** [comment]
We've tried using any trick in the book to get the currently published format bundled. Nothing worked. Perhaps we're missing something obvious, but it seems the umd format typescript generates is not compatible with bundling:
`WARNING in ./node_modules/vscode-css-languageservice/lib/parser/cssErrors.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`

Probably the `factory(require, exports)` expression is what breaks it. Other umd-generating solutions use statically-analyzable syntax `require('depA'), require('depB')` outside the `define` call as well.

It is true the number of files will be doubled in the npm package, but there are benefits as well:
- Broader compatibility with existing web bundling solutions (webpack, rollup, etc).
- Tree shaking. The es2015 module format makes this possible/easier.
- Only needed to be done during publishing.

There are several widely-used solutions already using multi-format publishing successfully:
- `react` publishes both umd and commonjs.
- `mobx-react` publishes both es2015 and umd.

We were not the first ones to encounter this issue, as someone published a fork 6 months ago with commonjs:
https://www.npmjs.com/package/vscode-css-languageservice-commonjs
Using a fork just for a module format feels just wrong (and is outdated? incompatible with current versions?)

**Comment by aeschli** [comment]
Other possible solutions:
- Find out how to make the UMD header webpack compatible and file an issue against TypeScript to adopt it: https://stackoverflow.com/questions/45929231/how-to-consume-an-umd-module-with-webpack claims to have a solution
- change our packager in the monaco language packages ([css](https://github.com/Microsoft/monaco-css), [html](https://github.com/Microsoft/monaco-html) and [json](https://github.com/Microsoft/monaco-json)) to take commonjs as input and generate amd from that (I think we could use webpack for that)

**Comment by amir-arad** [comment]
possible workaround:
[matt-gadd/umd-compat-loader](https://github.com/matt-gadd/umd-compat-loader) reverts the umd wrapping.

I've added the following to my webpack configuration (in `module>rules`):
```js
{
    test: /node_modules\/vscode-/,
    use: {loader: "umd-compat-loader"}
}
```

**Comment by akosyakov** [comment]
Repositories which also cannot be consumed with webpack:
- https://github.com/Microsoft/vscode-uri
- https://github.com/Microsoft/node-jsonc-parser
