### ISSUE TITLE
Less: $property gives error

### ISSUE THREAD

**Issue by Azganoth** [microsoft/vscode-css-languageservice#78]
![screenshot_235](https://user-images.githubusercontent.com/24205667/37710392-471a01f4-2cec-11e8-9bd5-0e06ae881f87.png)
![screenshot_236](https://user-images.githubusercontent.com/24205667/37710399-4c5bca8a-2cec-11e8-9b01-111cfb63ae25.png)

Giving error 'semi-colon expected' or 'property value expected'

**Comment by JosiahRooney** [comment]
I'm also having this issue, or at least very similar. The following code gives me an error in the editor of 

> [less] property value expected [css-propertyvalueexpected]

```
.rating {
  height: 20px;
  top: -$height / 2;
}
```

My code is compiled properly by Less and works fine. It's just showing an error in the editor.

**Comment by aeschli** [comment]
@Azganoth I don't see this error in the latest:
![image](https://user-images.githubusercontent.com/6461412/75028067-e82cba00-549f-11ea-9545-b7a8a3e2fb13.png)
Maybe it got fixed or the error comes from some other extension? (check the problems view)

**Comment by aeschli** [comment]
Same for the snippet that @JosiahRooney pasted:
![image](https://user-images.githubusercontent.com/6461412/75028190-20cc9380-54a0-11ea-8232-44880b00d262.png)

Closing issue.
