### ISSUE TITLE
[feature request] Support @apply

### ISSUE THREAD

**Issue by rictic** [Microsoft/vscode-css-languageservice#8]
The `@apply` rule is a [proposed spec](https://tabatkins.github.io/specs/css-apply-rule/#at-ruledef-apply) for implementing native mixins in CSS on top of [CSS Custom Properties](https://github.com/Microsoft/vscode-css-languageservice/issues/7).

It allows declarations like the following:

```css
body {
  @apply --my-theme;
}
```

This sees real world usage today, primarily from users of the Polymer library, which ships a polyfill. As of VSCode 1.7.1, this is a syntax error.

**Comment by aeschli** [comment]
Thanks for the heads-up. Given the amount of work to add new constructs to the parser, I'm always bit cautious adding proposed but not yet final language features.
Until then we have the option to disable css validation (`"css.validate": "false"`).

**Comment by rictic** [comment]
That's totally reasonable. Would you accept a patch that added this functionality?

The syntax is rather restrained (my read of the proposed spec is that it only accepts the literal text `@apply` then whitespace, then a css custom property name, optional whitespace, semicolon), so it won't give false positives for users that aren't intending to use the feature.

**Comment by aeschli** [comment]
Yes, a PR would be awesome.
You'd add a additional declaration at https://github.com/Microsoft/vscode-css-languageservice/blob/master/src/parser/cssParser.ts#L263m
similar to
https://github.com/Microsoft/vscode-css-languageservice/blob/master/src/parser/lessParser.ts#L180

Let me know if I can help. Please keep the changes minimal so I can easly review.

**Comment by philippelesaux** [comment]
Polymer user here, would love to see this merged, but with support for all @ rules

**Comment by rictic** [comment]
The css language server already has support for a number of `@` rules. Are there any others that you've noticed aren't recognized?

**Comment by philippelesaux** [comment]
Ah, didn't realize that. I was just getting the error on @apply, disregard that comment
