### ISSUE TITLE
[folding] handle intersecting folding regions 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-css-languageservice#85]
Folding ranges must not intersect. Region range should be given precedence.

The tests describe the expected bahaviour:
```ts
	test('region intersecting with declaration', () => {
		const input = [
			/*0*/'/* #region */',
			/*1*/'.bar {',
			/*2*/'  color: red;',
			/*3*/'/* #endregion */',
			/*4*/'  display: block;',
			/*5*/'}',
		];
		assertRanges(input, [r(0, 3, 'region')]);
	});	

	test('region intersecting with declaration 2', () => {
		const input = [
			/*0*/'.bar {',
			/*1*/'/* #region */',
			/*2*/'  color: red;',
			/*3*/'}',			
			/*4*/'/* #endregion */',
		];
		assertRanges(input, [r(1, 4, 'region')]);
	});
```

**Comment by aeschli** [comment]
We can discuss what the expected result is, if `#regions` win or if the first started range wins.

**Comment by octref** [comment]
I think in most cases, having intersected regions would not be what the user intends. I think the first started range sounds more consistent & reasonable. It's also easier to understand.

Another thought is to pass back intersection regions and let editor decide if it should render them all. This is like suggest where we pass back all the items and leave the filtering to editor. Other LSP compliant editors might choose to allow intersecting regions.
