### ISSUE TITLE
Question: extend/ integrate custom rules or remove diagnostics

### ISSUE THREAD

**Issue by eriklieben** [Microsoft/vscode-css-languageservice#9]
Not sure if this is a question for vs code itself or this language server, but I am wondering if it is possible to write code to disable diagnostic rules provided by the CSS language service or if I can hook into the CSS language service some way to tell it to allow customized CSS. 

I want to be able to allow users to use ```${foo}``` inside files with a ```.CSS``` extension but to archive that I think I need to ask users to disable the regular CSS diagnostics by using ```"css.validate": true,``` in their settings and clone/ implement the CSS diagnostics with the customized rule/ diagnostics. 

Do you know if there is a different/ better way to do this?

The syntax ```${foo}``` is used by Aurelia UX (https://github.com/aurelia/vscode-extension/issues/23)

Thanks in advance,

Erik

**Comment by aeschli** [comment]
You could define your won language id ('aureli') and write your own language server for it that uses the css language service library.
Your server would first replace (or white-out) the special syntax (${foo), then pass the modified content to the css service. Depending how it is done you'd have to map some positions on the results.
